CREATE TABLE "AccessKeys" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"key_value" TEXT NOT NULL,
	"label" TEXT,
	"user_id" INTEGER,
	"created_at" TIME,
	"exprires_at" TIME,
	PRIMARY KEY("id")
);

CREATE TABLE "Users" (
	"telegram_id" INTEGER NOT NULL,
	"is_admin" BOOLEAN,
	PRIMARY KEY("telegram_id")
);

ALTER TABLE "AccessKeys"
ADD FOREIGN KEY("user_id") REFERENCES "Users"("telegram_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
